include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*gr.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    invalid_assignment: error
    missing_return: error
    dead_code: error
    deprecated_member_use: warning
    avoid_print: warning
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    library_private_types_in_public_api: false
    prefer_single_quotes: false
    prefer_double_quotes: true
